using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;
public class WeaponAmmoUI : MonoBehaviour
{
    [SerializeField] TextMeshProUGUI weaponNameText;
    [SerializeField] TextMeshProUGUI currentBulletCountText;
    [SerializeField] TextMeshProUGUI totalBulletCountText;

    [SerializeField] WeaponComponent weaponComponent;

    private void Start()
    {
        PlayerEvents.OnWeaponEquipped += this.OnWeaponEquipped; 
    }

    private void OnDisable()
    {
        PlayerEvents.OnWeaponEquipped -= this.OnWeaponEquipped;
    }

    public void OnWeaponEquipped(WeaponComponent _weaponComponent)
    {
        weaponComponent = _weaponComponent;
    }

    // Update is called once per frame
    void Update()
    {
        if (!weaponComponent)
        {
            return;
        }

        weaponNameText.text = weaponComponent.weaponStats.weaponName;
        currentBulletCountText.text = weaponComponent.weaponStats.bulletsInClip.ToString();
        totalBulletCountText.text = weaponComponent.weaponStats.totalBullets.ToString();

    }
}
